services:
  setup:
    container_name: setup
    build:
      context: .
      dockerfile: docker/Dockerfile.cli
    volumes:
      - .:/find-a-friend
      - node_modules:/find-a-friend/node_modules
    environment:
      CI: true
    command: sh -lc "pnpm install"
    restart: "no"

  workspace:
    container_name: workspace
    build:
      context: .
      dockerfile: docker/Dockerfile.cli
    depends_on:
      setup:
        condition: service_completed_successfully
    volumes:
      - .:/find-a-friend
      - node_modules:/find-a-friend/node_modules
    command: sh -c "tail -f /dev/null"
    restart: "no"

  api:
    container_name: api
    build:
      context: .
      target: dev
      dockerfile: apps/api/Dockerfile
    depends_on:
      workspace:
        condition: service_started
      setup:
        condition: service_completed_successfully
    volumes:
      - .:/find-a-friend
      - node_modules:/find-a-friend/node_modules
    working_dir: /find-a-friend
    ports:
      - "3333:3333"

  postgres:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=findafriend

networks:
  default:
    name: find-a-friend
    driver: bridge

volumes:
  node_modules:
